# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='its2Seq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sequence', models.TextField()),
                ('length', models.IntegerField()),
                ('clade', models.CharField(max_length=10)),
                ('occurance', models.IntegerField()),
            ],
        ),
    ]
