# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='its2seq',
            old_name='occurance',
            new_name='occurrence',
        ),
    ]
