# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0002_auto_20170111_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionType', models.CharField(choices=[('fasta', 'fasta'), ('fastQ', 'fastQ')], max_length=5)),
                ('submittingUser', models.CharField(default='Bob', max_length=30)),
                ('submittedData', models.FileField(upload_to='')),
            ],
        ),
    ]
