# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0003_datasubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasubmission',
            old_name='submittedData',
            new_name='submittedDataRaw',
        ),
    ]
